name: anikki
description: The ultimate anime companion.

publish_to: 'none'

version: 1.0.0

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5
  crypto: ^3.0.3
  graphql: ^5.1.3
  simple_icons: ^7.10.0
  collection: ^1.17.1
  settings_ui: ^2.0.2
  shimmer: ^3.0.0
  path: ^1.8.3
  open_app_file: ^4.0.1
  audio_video_progress_bar: ^1.0.1
  protocol_handler: ^0.1.5
  flutter_dotenv: ^5.0.2
  url_launcher: ^6.1.11
  anitomy:
    path: packages/anitomy
  wakelock: ^0.6.2
  flutter_platform_widgets: ^3.3.4
  empty_widget: ^0.0.5
  flex_color_scheme: ^7.1.2
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  logger: ^1.3.0
  hydrated_bloc: ^9.1.1
  path_provider: ^2.0.15
  connectivity_plus: ^4.0.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  media_kit: ^0.0.11
  # For video rendering.
  media_kit_video: ^0.0.12
  # Enables support for higher number of concurrent instances. Optional.
  media_kit_native_event_loop: ^1.0.4
  # Windows package for video (& audio) native libraries.
  media_kit_libs_windows_video: ^1.0.2
  # iOS package for video (& audio) native libraries.
  media_kit_libs_ios_video: ^1.0.4
  # Android package for video native libraries.
  media_kit_libs_android_video: ^1.0.6
  # macOS package for video (& audio) native libraries.
  media_kit_libs_macos_video: ^1.0.5
  # Linux dependency package.
  media_kit_libs_linux: ^1.0.2
  watcher: ^1.1.0
  flutter_staggered_animations: ^1.1.1
  file_picker: ^5.2.9
  window_manager: ^0.3.4
  intl: ^0.18.1
  auto_size_text: ^3.0.0
  html: ^0.15.4
  http: ^0.13.6
  quiver: ^3.2.1
  youtube_explode_dart: ^1.12.4
  google_fonts: ^4.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

  flutter_lints: ^2.0.1
  test: ^1.21.4
  bloc_test: ^9.1.2
  mocktail: ^0.3.0
  build_runner: ^2.4.5
  graphql_codegen: ^0.12.2

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/images/placeholder.png
    - assets/images/cover_placeholder.jpg
