name: anikki
description: The ultimate anime companion.

publish_to: "none"

version: 1.0.0

environment:
  sdk: ">=3.1.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5
  crypto: ^3.0.3
  graphql: ^5.1.3
  simple_icons: ^7.10.0
  collection: ^1.17.2
  settings_ui: ^2.0.2
  shimmer: ^3.0.0
  path: ^1.8.3
  open_app_file: ^4.0.2
  audio_video_progress_bar: ^2.0.0
  protocol_handler: ^0.1.5
  flutter_dotenv: ^5.1.0
  url_launcher: ^6.1.12
  anitomy:
    path: packages/anitomy
  flutter_platform_widgets: ^3.3.5
  empty_widget: ^0.0.5
  flex_color_scheme: ^7.1.2
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  logger: ^2.0.1
  hydrated_bloc: ^9.1.2
  path_provider: ^2.0.15
  connectivity_plus: ^4.0.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  media_kit: 1.1.7
  # For video rendering.
  media_kit_video: 1.1.8
  # Enables support for higher number of concurrent instances. Optional.
  media_kit_native_event_loop: ^1.0.7
  # Windows package for video (& audio) native libraries.
  media_kit_libs_windows_video: ^1.0.8
  # iOS package for video (& audio) native libraries.
  media_kit_libs_ios_video: ^1.1.3
  # Android package for video native libraries.
  media_kit_libs_android_video: ^1.3.3
  # macOS package for video (& audio) native libraries.
  media_kit_libs_macos_video: ^1.1.3
  # Linux dependency package.
  media_kit_libs_linux: ^1.1.2
  watcher: ^1.1.0
  flutter_staggered_animations: ^1.1.1
  file_picker: ^5.2.9
  window_manager: ^0.3.5
  intl: ^0.18.1
  auto_size_text: ^3.0.0
  html: ^0.15.4
  http: ^1.1.0
  quiver: ^3.2.1
  youtube_explode_dart: ^2.0.2
  google_fonts: ^5.1.0
  flutter_animation_progress_bar: ^2.3.1
  screen_brightness: ^0.2.2
  marqueer:
    git:
      url: https://github.com/Kylart/marqueer
      ref: main
  ionicons: ^0.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

  flutter_lints: ^2.0.2
  test: ^1.24.1
  bloc_test: ^9.1.3
  mocktail: ^1.0.0
  build_runner: ^2.4.6
  graphql_codegen: ^0.13.5
  dart_pre_commit: ^5.2.0+1
  git_hooks: ^1.0.1

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/images/placeholder.jpg
    - assets/images/cover_placeholder.jpg

dart_pre_commit:
  outdated: false
  pull-up-dependencies: false
