name: anikki
description: The ultimate anime companion.

publish_to: "none"

version: 1.0.3

environment:
  sdk: ">=3.1.0"

dependencies:
  flutter:
    sdk: flutter

  ## Icons
  cupertino_icons: ^1.0.6
  # https://ionic.io/ionicons/
  ionicons: ^0.2.2
  # https://simpleicons.org
  simple_icons: ^7.10.0

  ## Bloc
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  hydrated_bloc: ^9.1.2

  ## Helpers
  collection: ^1.17.2
  crypto: ^3.0.3
  encrypt: ^5.0.3
  graphql: ^5.1.3
  file_picker: ^6.1.1
  flex_color_scheme: ^7.3.1
  flutter_dotenv: ^5.1.0
  html: ^0.15.4
  http: ^1.1.0
  open_app_file: ^4.0.2
  path: ^1.8.3
  path_provider: ^2.1.1
  protocol_handler: ^0.1.6
  quiver: ^3.2.1
  screen_brightness: ^0.2.2+1
  talker: ^3.2.0
  talker_flutter: ^3.6.0
  talker_logger: ^3.1.0
  talker_bloc_logger: ^2.4.0
  url_launcher: ^6.1.14
  watcher: ^1.1.0
  window_manager: ^0.3.6
  yaml: ^3.1.2
  youtube_explode_dart: ^2.0.2

  ## Widgets
  anitomy:
    path: packages/anitomy
  audio_video_progress_bar: ^2.0.0
  auto_size_text: ^3.0.0
  connectivity_plus: ^5.0.2
  device_preview: ^1.1.0
  equatable: ^2.0.5
  flutter_animation_progress_bar: ^2.3.1
  flutter_platform_widgets: ^6.0.2
  flutter_staggered_animations: ^1.1.1
  google_fonts: ^6.1.0
  marqueer:
    git:
      url: https://github.com/Kylart/marqueer
      ref: main
  media_kit: ^1.1.10 # Primary package.
  media_kit_video: ^1.2.4 # For video rendering.
  media_kit_libs_video: ^1.0.4 # Native video dependencies.
  settings_ui: ^2.0.2
  shimmer: ^3.0.0

  ## Database
  hive: ^2.2.3
  hive_flutter: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

  flutter_lints: ^3.0.1
  test: ^1.24.1
  bloc_test: ^9.1.4
  mocktail: ^1.0.0
  build_runner: ^2.4.6
  graphql_codegen: ^0.13.7
  dart_pre_commit: ^5.2.0+1
  git_hooks: ^1.0.1
  flutter_launcher_icons: "^0.13.1"

flutter:
  uses-material-design: true

  assets:
    - pubspec.yaml
    - .env
    - assets/images/placeholder.jpg
    - assets/images/cover_placeholder.jpg
    - assets/images/jinrui.png

dart_pre_commit:
  outdated: false
  pull-up-dependencies: false

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/rectangle_logo.png"
  min_sdk_android: 21
  adaptive_icon_background: "#9dd4fd"
  # Help here https://www.youtube.com/watch?v=eMHbgIgJyUQ
  adaptive_icon_foreground: "assets/icon_foreground.png"
  windows:
    generate: true
    image_path: "assets/circle_logo.png"
    icon_size: 256 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/rectangle_logo.png"
