name: qbittorrent
description: An interface to remotely control a QBitTorrent instance.
version: 1.0.0

environment:
  sdk: ^3.0.0

# Add regular dependencies here.
dependencies:
  equatable: ^2.0.5
  http: ^0.13.5

dev_dependencies:
  lints: ^2.0.0
