display_name: Anikki
package_name: com.kylart.anikki
maintainer:
  name: Kylart
  email: kylart.dev@gmail.com
co_authors:
  - name: Kylart
    email: kylart.dev@gmail.com
priority: optional
essential: false
icon: assets/logo.png

keywords:
  - Anime
  - Companion

generic_name: Anime Application

categories:
  - Media

section: x11
installed_size: 6604

postinstall_scripts:
  - echo "Installed."
postuninstall_scripts:
  - echo "Successfully uninstalled"

startup_notify: false