name: anilist
description: Package to query Anilist.co
version: 1.0.0
publish_to: none

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  graphql: ^5.1.3
  simple_icons: ^7.10.0
  crypto: ^3.0.2
  collection: ^1.16.0
  graphql_flutter: ^5.1.2

dev_dependencies:
  build_runner: ^2.3.3
  graphql_codegen: ^0.12.0-beta.18
  test: ^1.21.4

