on:
  push:
    branches:
      - master

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: "true"

      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          cache: true

      - name: Install Ninja
        run: |
          sudo apt-get update -y
          sudo apt-get install -y ninja-build libgtk-3-dev

      - name: Env setup
        run: |
          touch .env
          echo "ANILIST_ID=${{ secrets.ANILIST_ID }} >> .env"
          cat .env

      - name: "Config"
        run: flutter config --enable-linux-desktop

      - name: "Debug build"
        run: flutter build linux --debug

      - name: "Test"
        run: flutter test

  build-desktop:
    needs: tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: "true"

      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          cache: true

      - name: Install Ninja
        run: |
          sudo apt-get update -y
          sudo apt-get install -y ninja-build libgtk-3-dev

      - name: Env setup
        run: |
          touch .env
          echo "ANILIST_ID=${{ secrets.ANILIST_ID }} >> .env"
          cat .env

      - name: "Config"
        run: flutter config --enable-linux-desktop

      - name: "Debug build"
        run: flutter build linux --debug

      - name: "Test"
        run: flutter test

      - name: "Release build"
        run: flutter build linux

  build-android:
    needs: tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: "true"

      - uses: actions/setup-java@v3
        with:
          distribution: "zulu"
          java-version: "17"

      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          cache: true

      - name: Install Ninja
        run: |
          sudo apt-get update -y
          sudo apt-get install -y ninja-build libgtk-3-dev

      - name: Env setup
        run: |
          touch .env
          echo "ANILIST_ID=${{ secrets.ANILIST_ID }} >> .env"
          cat .env

      - name: "Release build"
        run: flutter build apk
