on:
  push:
    branches:
    - master

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: "true"
      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
      - name: 'Config'
        run: flutter config --enable-macos-desktop

      - name: 'Debug build'
        run: flutter build macos --debug --verbose

      - name: 'Test'
        run: flutter test

      - name: 'Release build'
        run: flutter build macos
